Stage 1
zer66607/market pull request #1
Opened 2018-02-17 19:54 UTC by zer66607

Ну вроде всё что надо работает.

2018-02-18 09:43 UTC, bluzir requested changes
Все оки, давай улучшим функцию main, чтобы она не была такой огромной

2018-02-18 09:43 UTC, bluzir commented on main.py
> +def main():
Все хорошо, но функция огромная
Давай думать, как разбить ее на подфункции, чтобы main() только вызвал эту подфункции и делал минимум локини

2018-02-18 09:43 UTC, bluzir commented on main.py
> +            if 'message' in last_update:
Во первых можешь сделать функцию обработчик сообщений из update (50-70 строки)

2018-02-18 09:43 UTC, bluzir commented on main.py
> +            if last_chat_text == start:
во вторых функцию обработки комманд (77-94 строки)

2018-02-18 10:40 UTC, zer66607 commented
Добавил новые функции в класс, для формирования сообщений и обработки текущего апдейта

2018-02-20 14:49 UTC, bluzir approved these changes
Неплохо. Оформление кода только улучшить — прийдет с опытом.

2018-02-20 14:49 UTC, bluzir commented on main.py
> +        resp = requests.get(self.api_url + method, params)
resp не очень название для переменной. 

лучше без сокращений

2018-02-20 14:49 UTC, bluzir commented on main.py
> +        tick = requests.get(self.api_coin_url + ticker + '-usd')
Тоже сокращения. Не нужно

2018-02-20 14:49 UTC, bluzir commented on main.py
> +        print('user: ' + last_chat_name)
В итогой версии принтов быть не должно. Если логгировать, то лучше через logging

2018-02-20 14:49 UTC, bluzir commented on main.py
> +                # print(last_chat)
без комменатриев на гитхабе лучше

2018-02-20 14:49 UTC, bluzir commented on main.py
> +    while True:
слишком

много

пробелов

2018-02-20 14:49 UTC, bluzir commented on main.py
> +    while True:
можно ограничиться одним двумя для разделения логики, но для каждую конструкцию отделять не нужно

2018-02-20 14:49 UTC, bluzir commented on main.py
> +        print('user: ' + last_chat_name)
Принты это для отладки во время разработки

2018-02-20 14:49 UTC, merged