Stage 2
zer66607/market pull request #2
Opened 2018-02-23 10:42 UTC by zer66607

Выглядит не очень, но с заданием справляется.

2018-02-23 19:43 UTC, bluzir requested changes
Найс. Начинай добавлять больше болей для товара, например изображение 

Плюс если будет время можно начинать пагинацию (спросить у меня в чате)

2018-02-25 20:43 UTC, zer66607 commented
В целом работает, но есть момент с наследованием блоков, не успел разобраться почему категории не хотят через наследование отображаться.

2018-02-25 21:06 UTC, zer66607 commented
Пофиксил категории в левом меню. Но так и не понял почему через наследование не получилось такое провернуть.

2018-02-27 06:19 UTC, bluzir approved these changes
Миграции и картинки лучше заигнорить

2018-02-27 06:19 UTC, bluzir commented on django_site/zerShop/migrations/0005_auto_20180224_2206.py
> +# Generated by Django 2.0.2 on 2018-02-24 19:06
папку миграций лучше тоже заигнорить

2018-02-27 06:19 UTC, bluzir commented on django_site/zerShop/views.py
> +    queryset = Product.objects.all()
Тут кверисет и модел одинаково работают, кверисет можно использовать, когда нужно отфильтрованный список товаров передать, например

2018-02-27 06:19 UTC, merged